##############################################################
#                                                            #
#                                                            #
#                     Coded by n1zamu!                       #
#                                                            #
#                                                            #
##############################################################

messages:

  # ПлэйсХолдер - %time% - время оставшееся для использования чата!

  noPermission: "&fУ вас нет прав для перезагрузки кулдаунов" # Текст при отсутствие прав на использование команд
  unknownUsage: "&fИспользование: /ncooldowns reload" # Текст при перезагрузке базы данных для администрации
  successfullyReload: "&cКулдауны успешно перезагружены!" # Текст при перезагрузке базы данных для администрации
  joinMessage: "&fТы новичок на сервере! Отыграй &6%time% чтобы писать в чат!" # Текст для новичка на сервере
  blockMessage: "&fТы еще не отыграл время! Подожди &6%time%!" # Текст при попытке отправить сообщение от игрока, который не отыграл время.
  notEnoughArgumentsMessage: "&fНедостаточно аргументов!" # Текст при недостатке элементов для отправки команды
  doubleDotMessage: "&fКоманды через двоеточие запрещены!" # Текст при отправке команды через двоеточие

cooldown: 600 # Задержка для новичков на сервере!
doubleDotCommands: true # Отключение команд через двоеточие, по типу minecraft:me
notification: # Оповещение игрока о прошедшем времени

  sound: true # Звук при оповещении игрока
  soundType: "ENTITY_EXPERIENCE_ORB_PICKUP" # Тип звука при оповещении

  message: true # В виде сообщения в чат
  title: false # В виде сообщения на весь экран
