name: nCooldowns
version: '1'
main: wtf.n1zamu.NCooldowns
api-version: '1.16'
author: n1zamu
commands:
  nCooldowns:
    permission: nCooldowns.reload
    aliases:
      - nCooldowns
    usage:
permissions:
  nCooldowns.reload:
    description: Право на перезагрузку базы данных!
  nCooldowns.bypass:
    description: Право на обход блокировки чата!
  nCooldowns.doubleDot:
    description: Право на обход команд через двоеточие!
